name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        wait-time: [0,0,0,180,300,360]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: sleep ${{ matrix.wait-time }}
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Dump GitHub job.container
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.job.container) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name : get job id 
        run: curl \
               -H "Accept:application/vnd.github.v3+json" \ 
               -H "authorization:Bearer ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_id}}/jobs
              
